global:
  scrape_interval: 1s
  evaluation_interval: 1s
rule_files:
- 'prometheus.rules'
scrape_configs:
- job_name: cluster_monitoring
  scrape_interval: 10s
  consul_sd_configs:
  - server: '172.31.0.5:8500'
    datacenter: application
    services: ['lb_cluster', 'worker_cluster', 'app_docker_cluster']
  relabel_configs:
  - source_labels: ['__meta_consul_service']
    regex:         '(.*)'
    target_label:  'job'
    replacement:   '$1'
  - source_labels: ['__meta_consul_service']
    regex:         '(.*)'
    target_label:  'group'
    replacement:   '$1'
- job_name: job_queuer
  scrape_interval: 5s
  static_configs:
    - targets: ['172.31.0.1:9102']
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "172.31.0.3:9093"
